### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by macbre** [Wikia/ask-fandom#14]
* [Linked Data at the BBC](http://www.pilod.nl/w/images/2/29/7OliverBartlett_PilotLinkedData_Keynote1.pdf)
* [`schema.org` and data scraping](https://kb.apify.com/tips-and-tricks/scraping-data-from-websites-using-schemaorg-microdata)
* [JSON-LD](https://json-ld.org/primer/latest/)
* [SPARQL](https://en.wikipedia.org/wiki/SPARQL)
* [RDF](http://www.linkeddatatools.com/introducing-rdf-part-2) + [RDF](http://www.inf.unibz.it/~nutt/Teaching/SemTechs1415/SemTechsSlides/2-RDF.pdf)

## Storage

* [Cayley](https://cayley.io/)

### SQL

```
Object		Property	Value
================================================
Star Wars	composer	John Williams
dynamite	inventor	Alfred Nobel
```

```
objects:
  object_id: int
  object_name: text
  object_type: text [mapped after schema.org types]

values:
  object_id: int
  property: text
  value: text
  links_to: int [points to another object, NULL - value is not "linkable"]
```

### RDF

```
@prefix wikipedia: <http://en.wikipedia.org/>
@prefix starwars: <http://starwars.fandom.com/>
@prefix dbo: <http://example.org/terms/>
@prefix schema: <http://schema.org/>

starwars:Star_Wars dbo:type schema:Movie ;
    schema:composer starwars:John_Williams .
wikipedia:Dynamite dbo:inventor wikipedia:Alfred_Nobel .

<http://dbpedia.org/resource/Semantic_Web>      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>       <http://dbpedia.org/ontology/Software> .
````

> https://starwars.fandom.com/wiki/John_Williams / https://schema.org/composer

* [`rdflib`](https://github.com/RDFLib/rdflib) + [RDF building example](https://github.com/RDFLib/rdflib/blob/master/examples/resource.py)
* [SMW RDF file](https://poznan.fandom.com/wiki/Specjalna:EksportRDF/Karol_Libelt)

### JSON-LD

* https://github.com/edsu/microdata
